name: Deploy on Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku 
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  
        with:
          email: synergia.soporte@gmail.com 
          api_key: cdfe16e7-388a-4aa7-a09f-ea8d16d264b4 
          app_name: nginx-moni 
          dockerfile: ./