name: Deploy on Heroku

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          email: ${{ secrets.USER_EMAIL }}
          api_key: ${{ secrets.HEROKU_KEY }}
          app_name: ${{ secrets.HEROKU_PROJET }}
          dockerfile: ./
