name: Deploy on Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: synergia.soporte@gmail.com # your heroku email
          api_key: cdfe16e7-388a-4aa7-a09f-ea8d16d264b4 # your  heroku api key
          app_name: nginx-moni # you aplication name
          dockerfile: ../ # set the path to the folder wher the Dokerfile is located
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web